/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpAuthorizeRouteImport } from './routes/mcp/authorize'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedNewProjectRouteImport } from './routes/_authed/new-project'
import { Route as AuthedCockpitRouteImport } from './routes/_authed/_cockpit'
import { Route as AuthedCockpitSettingsRouteImport } from './routes/_authed/_cockpit/settings'
import { Route as AuthedCockpitCockpitRouteImport } from './routes/_authed/_cockpit/cockpit'
import { Route as AuthedCockpitAutoshipRouteImport } from './routes/_authed/_cockpit/autoship'
import { Route as AuthedCockpitAnalyticsRouteImport } from './routes/_authed/_cockpit/analytics'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: '/mcp/authorize',
  path: '/mcp/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedNewProjectRoute = AuthedNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCockpitRoute = AuthedCockpitRouteImport.update({
  id: '/_cockpit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCockpitSettingsRoute = AuthedCockpitSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedCockpitRoute,
} as any)
const AuthedCockpitCockpitRoute = AuthedCockpitCockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => AuthedCockpitRoute,
} as any)
const AuthedCockpitAutoshipRoute = AuthedCockpitAutoshipRouteImport.update({
  id: '/autoship',
  path: '/autoship',
  getParentRoute: () => AuthedCockpitRoute,
} as any)
const AuthedCockpitAnalyticsRoute = AuthedCockpitAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedCockpitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/new-project': typeof AuthedNewProjectRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/analytics': typeof AuthedCockpitAnalyticsRoute
  '/autoship': typeof AuthedCockpitAutoshipRoute
  '/cockpit': typeof AuthedCockpitCockpitRoute
  '/settings': typeof AuthedCockpitSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/new-project': typeof AuthedNewProjectRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/analytics': typeof AuthedCockpitAnalyticsRoute
  '/autoship': typeof AuthedCockpitAutoshipRoute
  '/cockpit': typeof AuthedCockpitCockpitRoute
  '/settings': typeof AuthedCockpitSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authed/_cockpit': typeof AuthedCockpitRouteWithChildren
  '/_authed/new-project': typeof AuthedNewProjectRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/_authed/_cockpit/analytics': typeof AuthedCockpitAnalyticsRoute
  '/_authed/_cockpit/autoship': typeof AuthedCockpitAutoshipRoute
  '/_authed/_cockpit/cockpit': typeof AuthedCockpitCockpitRoute
  '/_authed/_cockpit/settings': typeof AuthedCockpitSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/new-project'
    | '/auth/callback'
    | '/mcp/authorize'
    | '/analytics'
    | '/autoship'
    | '/cockpit'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/new-project'
    | '/auth/callback'
    | '/mcp/authorize'
    | '/analytics'
    | '/autoship'
    | '/cockpit'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/_authed/_cockpit'
    | '/_authed/new-project'
    | '/auth/callback'
    | '/mcp/authorize'
    | '/_authed/_cockpit/analytics'
    | '/_authed/_cockpit/autoship'
    | '/_authed/_cockpit/cockpit'
    | '/_authed/_cockpit/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  McpAuthorizeRoute: typeof McpAuthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/authorize': {
      id: '/mcp/authorize'
      path: '/mcp/authorize'
      fullPath: '/mcp/authorize'
      preLoaderRoute: typeof McpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/new-project': {
      id: '/_authed/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof AuthedNewProjectRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_cockpit': {
      id: '/_authed/_cockpit'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedCockpitRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_cockpit/settings': {
      id: '/_authed/_cockpit/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedCockpitSettingsRouteImport
      parentRoute: typeof AuthedCockpitRoute
    }
    '/_authed/_cockpit/cockpit': {
      id: '/_authed/_cockpit/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof AuthedCockpitCockpitRouteImport
      parentRoute: typeof AuthedCockpitRoute
    }
    '/_authed/_cockpit/autoship': {
      id: '/_authed/_cockpit/autoship'
      path: '/autoship'
      fullPath: '/autoship'
      preLoaderRoute: typeof AuthedCockpitAutoshipRouteImport
      parentRoute: typeof AuthedCockpitRoute
    }
    '/_authed/_cockpit/analytics': {
      id: '/_authed/_cockpit/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedCockpitAnalyticsRouteImport
      parentRoute: typeof AuthedCockpitRoute
    }
  }
}

interface AuthedCockpitRouteChildren {
  AuthedCockpitAnalyticsRoute: typeof AuthedCockpitAnalyticsRoute
  AuthedCockpitAutoshipRoute: typeof AuthedCockpitAutoshipRoute
  AuthedCockpitCockpitRoute: typeof AuthedCockpitCockpitRoute
  AuthedCockpitSettingsRoute: typeof AuthedCockpitSettingsRoute
}

const AuthedCockpitRouteChildren: AuthedCockpitRouteChildren = {
  AuthedCockpitAnalyticsRoute: AuthedCockpitAnalyticsRoute,
  AuthedCockpitAutoshipRoute: AuthedCockpitAutoshipRoute,
  AuthedCockpitCockpitRoute: AuthedCockpitCockpitRoute,
  AuthedCockpitSettingsRoute: AuthedCockpitSettingsRoute,
}

const AuthedCockpitRouteWithChildren = AuthedCockpitRoute._addFileChildren(
  AuthedCockpitRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCockpitRoute: typeof AuthedCockpitRouteWithChildren
  AuthedNewProjectRoute: typeof AuthedNewProjectRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCockpitRoute: AuthedCockpitRouteWithChildren,
  AuthedNewProjectRoute: AuthedNewProjectRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  McpAuthorizeRoute: McpAuthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
